[project]
name = "booking-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"aiosqlite>=0.22.1",
	"asyncpg>=0.31.0",
	"fastapi[standard]",
	"httpx>=0.28.1",
	"pyjwt>=2.10.1",
	"redis>=7.1.0",
	"sqlmodel>=0.0.30",
]
